typography_spectrum: 0.17626996750390103
color:
  brandStrength: 0.6289521459349902
  lightness: 0.1667683192071422
  saturation: 0.23453220562557553
  rhythmicContrast: 0.26131643031456386
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
layout_spectrum: 0.080798094522042
author:
  name: wala!
logo: null
name: wala music
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: facebook
    url: 'https://www.facebook.com/WALAmusic'
    type: external
  - name: soundcloud
    url: 'https://soundcloud.com/wala'
    type: external
  - name: youtube
    url: 'https://www.youtube.com/user/theWALAmusic'
    type: external
  - name: instagram
    url: 'https://www.instagram.com/walamusic/'
    type: external
  - name: support my music
    url: 'https://walamusic.bandcamp.com/music'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/06062c2a-9fa0-4832-8104-a8729266fecc.jpg
title: wala music
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2F00Bo8PdRSaE%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D00Bo8PdRSaE&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2F00Bo8PdRSaE%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: AwakenToLucidity
          url: 'https://www.youtube.com/user/AwakenToLucidity'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: www.youtube.com
      keywords:
        - duration
        - lucidity
        - views
        - walamusic
        - http
        - festival
        - wala
        - https
        - www
        - remix
      description: >-
        FREE DOWNLOAD of the track @ https://www.facebook.com/WALAmusic Get your
        SUBWOOFERS and HEADPHONES out, FULL SCREEN 1080P and ENJOY!
      inLanguage: en
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=00Bo8PdRSaE&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=00Bo8PdRSaE&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=00Bo8PdRSaE&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=00Bo8PdRSaE&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=00Bo8PdRSaE&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=00Bo8PdRSaE'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=00Bo8PdRSaE
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=00Bo8PdRSaE
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=00Bo8PdRSaE'
      title: WALA - Whatever You Like @ Lucidity Festival
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Electronic Music Producer | Ableton Live Educator | Late-night Ninja Baker |
  Muse
purpose:
  - type: external
    url: 'https://walamusic.bandcamp.com/merch/private-ableton-lesson'
    label: private ableton lessons!
  - type: contact
    url: 'mailto:walasounds@gmail.com'
    label: booking
github: true
